<?php

/**
 * BaseaVideoSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseaVideoSlot extends aSlot
{
    public function setUp()
    {
        parent::setUp();
        
    }
}