<?php

/**
 * BaseaSlideshowSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    content
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class BaseaSlideshowSlot extends aSlot
{
    public function setUp()
    {
        parent::setUp();
        
    }
}